### ISSUE TITLE
Cannot load prawn

### ISSUE THREAD

**Issue by floer32** [lord/mortalical#1]
I don't know Ruby much so I don't know the nature of this yet, but I got this error today.

```
$ ruby generate.rb 1990 --letter
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- prawn (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/x/Workspace/mortalical/calendar.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from generate.rb:1:in `<main>'
```

Here was the output when I did `bundle install`, if that's helpful 

```
$ bundle install --path vendor/bundle
Fetching gem metadata from https://rubygems.org/...............
Installing pdf-core 0.4.0
Installing ttfunk 1.4.0
Installing prawn 1.3.0
Using bundler 1.7.3
Your bundle is complete!
It was installed into ./vendor/bundle
Post-install message from prawn:

  ********************************************


  A lot has changed recently in Prawn.

  Please read the changelog for details:

  https://github.com/prawnpdf/prawn/wiki/CHANGELOG


  ********************************************
```

**Comment by floer32** [comment]
I tried constraining my version of `prawn` to an older one (just tried to cross reference the timing from your repo and `prawn`. Didn't help:

```
$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Installing pdf-core 0.4.0
Installing ttfunk 1.4.0
Using bundler 1.12.5
Installing prawn 1.3.0
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from prawn:

  ********************************************


  A lot has changed recently in Prawn.

  Please read the changelog for details:

  https://github.com/prawnpdf/prawn/wiki/CHANGELOG


  ********************************************


$ ruby generate.rb 1990 --letter
/Users/x/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- prawn (LoadError)
    from /Users/x/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/x/Workspace/mortalical/calendar.rb:1:in `<top (required)>'
    from /Users/x/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/x/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from generate.rb:1:in `<main>'
```

Would love to help more but I'm very unfamiliar with Ruby and bundling I guess. I may tinker more...
